### ISSUE TITLE
使用此主题后如何替换首页文章默认的缩略图？

### ISSUE THREAD

**Issue by starlight02** [halo-dev/halo-theme-siren#2]
目前默认的缩略图使用的是 `.halo/templates/themes/louie_senpai_siren/images/temp.jpg` 这个图片，我想更换，尝试手动替换了该图片，但是默认的缩略图并没有更改，想请教该如何设置？

**Comment by ruibaby** [comment]
主题设置。

**Comment by starlight02** [comment]
差点忘了，手动替换改图片确实有用，当时没有更换应该是服务器缓存问题。
