### ISSUE TITLE
点进去某一篇博客后顶部没有图片

### ISSUE THREAD

**Issue by AmosWong1998** [halo-dev/halo-theme-siren#5]
![image](https://user-images.githubusercontent.com/41744494/73172565-433bed00-413e-11ea-94bc-e3e56ff2aba4.png)
如上图所示 
是我没有找到设置的选项还是因为本身就没有这个功能？

**Comment by ruibaby** [comment]
文章设置里可以设置缩略图。

**Comment by AmosWong1998** [comment]
原来如此 非常感谢 @ruibaby
