### ISSUE TITLE
升级到1.31版本后，所有文章都打不开了 

### ISSUE THREAD

**Issue by riocwong** [halo-dev/halo-theme-siren#9]
升级到1.31版本后，所有文章都打不开了 
500
Internal Server Error.
Request processing failed; nested exception is org.springframework.context.ApplicationContextException: Failed to parse [themes/louie_senpai_siren/archives.ftl]; nested exception is freemarker.core.ParseException: Syntax error in template "themes/louie_senpai_siren/archives.ftl" in line 19, column 112: Encountered "\')>\n

\U6587\U7AE0\U5F52\U6863
\n \n
\n <@postTag method=\"archiveMonth\">\n <#list archives as archive>\n
\n \n
${archive.year?c}-${archive.month!}
\n
\n <#list archive.posts as post>\n \n
\n
\n \n ${post.createTime?string(\'", but was expecting one of: "." ".." "..*" "?" "??" "!" "[" "(" "}" "." "[" "(" "?" "!" "??" "..*" ".."

**Comment by riocwong** [comment]
原来在线更新 不好使，需要zip上传一下，解决了

**Comment by ruibaby** [comment]
> 原来在线更新 不好使，需要zip上传一下，解决了

目前是直接使用的 Github，可能部分服务器会访问很慢或者超时，后面我们会考虑处理这个问题。
